### ISSUE TITLE
Where do I specify the collection?

### ISSUE THREAD

**Issue by leonpotgieter** [tomeglenn/documental#1]
Hi, thanks I'm keen to try documental out...
Just not finding a place where I can specify the collection I wish to use and don't see anything in your documentation explaining that...  can you advise?
Thanks
Leon

**Comment by tomglenn** [comment]
Hi Leon, thanks for checking Documental out.
To specify the collection you decorate your POCO with the `[DocumentType("collection-name")]` attribute.

Hope this helps, let me know if you are still having issues.
